name: Test

on:
  workflow_call:
    inputs:
      os:
        description: "The os the workflow shold use"
        required: false
        type: string
        default: ubuntu-latest

permissions:
  checks: write
  contents: write

jobs:
  test-build:
    name: "Run Tests"
    runs-on: ${{ inputs.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: "rustfmt"

      - run: cargo test --all-features
